services:
  postgres:
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_db:/var/lib/postgesql/data
    networks:
      - app-network

volumes:
  pg_db:
networks:
  app-network:
    driver: bridge